/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <stdio.h>

#include "OSMCAL_interface.h"
#include "main.h"

#include "RCC_Private.h"
#include "RCC_Interface.h"

#include "GPIO_prv.h"
#include "GPIO_interface.h"

int main(void)
{

	EnableSystemFaults();

	STK_voidInit(1000);

	Stack_voidSchedulerStackInit(SCHED_TASK_STACK);

	InitTaskStack();

	ChangeToPSP();

	Task1_Handler();

	/* Loop forever */
	for(;;);
}


void Task1_Handler(void)
{
	while(1)
	{
		printf("Hello!, form Task1\r\n");
	}
}
void Task2_Handler(void)
{
	while(1)
	{
		printf("Hello!, form Task2\r\n");
	}
}
void Task3_Handler(void)
{
	while(1)
	{
		printf("Hello!, form Task3\r\n");
	}
}
void Task4_Handler(void)
{
	while(1)
	{
		printf("Hello!, form Task4\r\n");
	}
}

