/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>

#include "OSMCAL_cfg.h"
#include "OSMCAL_interface.h"

#include "main.h"

#include "RCC_Private.h"
#include "RCC_Interface.h"

#include "GPIO_prv.h"
#include "GPIO_interface.h"

#define CHANNEL1_PORT		PORTC
#define CHANNEL1_PIN		PIN8

#define CHANNEL2_PORT		PORTC
#define CHANNEL2_PIN		PIN6

#define CHANNEL3_PORT		PORTC
#define CHANNEL3_PIN		PIN5

#define CHANNEL4_PORT		PORTC
#define CHANNEL4_PIN		PIN9

#define DELAY_COUNT_1MS	1250U
#define DELAY_COUNT_1S	(1000*(DELAY_COUNT_1MS))
#define DELAY_COUNT_500MS	(500*(DELAY_COUNT_1MS))
#define DELAY_COUNT_250MS	(250*(DELAY_COUNT_1MS))
#define DELAY_COUNT_125MS	(125*(DELAY_COUNT_1MS))

void Delay(uint32_t Count)
{
	uint32_t i;
	for(i=0; i<Count ;i++);

}
int main(void)
{

	PinConfig_t CHANNEL1 = {

			.AltFunc        = AF4,
			.Mode           = OUTPUT,
			.OutputType     = PUSH_PULL,
			.PinNum         = CHANNEL1_PIN,
			.Port           = CHANNEL1_PORT,
			.PullType       = NOPULL,
			.Speed			= LOW_SPEED

	};
	PinConfig_t CHANNEL2 = {

				.AltFunc        = AF4,
				.Mode           = OUTPUT,
				.OutputType     = PUSH_PULL,
				.PinNum         = CHANNEL2_PIN,
				.Port           = CHANNEL2_PORT,
				.PullType       = NOPULL,
				.Speed			= LOW_SPEED

		};
	PinConfig_t CHANNEL3 = {

				.AltFunc        = AF4,
				.Mode           = OUTPUT,
				.OutputType     = PUSH_PULL,
				.PinNum         = CHANNEL3_PIN,
				.Port           = CHANNEL3_PORT,
				.PullType       = NOPULL,
				.Speed			= LOW_SPEED

		};
	PinConfig_t CHANNEL4 = {

				.AltFunc        = AF4,
				.Mode           = OUTPUT,
				.OutputType     = PUSH_PULL,
				.PinNum         = CHANNEL4_PIN,
				.Port           = CHANNEL4_PORT,
				.PullType       = NOPULL,
				.Speed			= LOW_SPEED

		};

	RCC_AHB1EnableClock(GPIOCEN);

	GPIO_u8PinInit(&CHANNEL1);
	GPIO_u8PinInit(&CHANNEL2);
	GPIO_u8PinInit(&CHANNEL3);
	GPIO_u8PinInit(&CHANNEL4);

	EnableSystemFaults();

	STK_voidInit(1000);

	Stack_voidSchedulerStackInit(SCHED_TASK_STACK);

	InitTaskStack();

	ChangeToPSP();

	Task1_Handler();

	/* Loop forever */
	for(;;);
}


void Task1_Handler(void)
{
	while(1)
	{
		GPIO_u8TogglePinValue(CHANNEL1_PORT, CHANNEL1_PIN);
		TaskDelay(1000);
	}
}
void Task2_Handler(void)
{
	while(1)
	{
		GPIO_u8TogglePinValue(CHANNEL2_PORT, CHANNEL2_PIN);
		TaskDelay(500);
	}
}
void Task3_Handler(void)
{
	while(1)
	{
		GPIO_u8TogglePinValue(CHANNEL3_PORT, CHANNEL3_PIN);
		TaskDelay(250);
	}
}
void Task4_Handler(void)
{
	while(1)
	{
		GPIO_u8TogglePinValue(CHANNEL4_PORT, CHANNEL4_PIN);
		TaskDelay(125);
	}
}

